name: alnsher
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.3.3
  bloc: ^8.1.2
  flutter_screenutil: ^5.9.0
  flutter_localizations:
    sdk: flutter
  intl: any
  fluttertoast: ^8.2.2
  shared_preferences: ^2.2.2
  blurrycontainer: 1.0.2
  carousel_slider: ^4.2.1
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  dropdown_textfield: ^1.0.8
  cached_network_image: ^3.3.1
  change_app_package_name: ^1.1.0
  webview_flutter: ^3.0.0
  checkout_screen_ui: ^1.0.1

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1

  android: "launcher_icon"
  ios: true
  image_path: "assets/images/dark-logo.png"
  min_sdk_android: 21
  change_app_package_name: ^1.1.0




flutter:
  uses-material-design: true

  assets:
     - assets/images/

  fonts:
   - family: 'urw'
     fonts:
       - asset: assets/fonts/font.ttf
